curl -X 'GET' \
  'http://127.0.0.1:8000/blog/1' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGV4QGdtYWlsLmNvbSIsImV4cCI6MTYyMDE5MjM0NX0.GukxyFxQh_cW0nqQRppmxrp3cJwSP9yoq657JTUFvWw'